version: "3"

services:

  activemq:
    image: webcenter/activemq:5.14.3
    ports:
      # mqtt
      - "1883:1883"
      # amqp
      - "5672:5672"
      # ui
      - "8161:8161"
      # stomp
      - "61613:61613"
      # ws
      - "61614:61614"
      # jms
      - "61616:61616"
    networks: [backing-services]
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: password
      ACTIVEMQ_WRITE_LOGIN: write
      ACTIVEMQ_WRITE_PASSWORD: password
      ACTIVEMQ_READ_LOGIN: read
      ACTIVEMQ_READ_PASSWORD: password
      ACTIVEMQ_JMX_LOGIN: jmx
      ACTIVEMQ_JMX_PASSWORD: password
      ACTIVEMQ_STATIC_TOPICS: static-topic-1;static-topic-2
      ACTIVEMQ_STATIC_QUEUES: static-queue-1;static-queue-2
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048

  postgres:
    image: healthcheck/postgres:alpine
    container_name: postgres
    ports:
      - 5432:5432
    networks: [backing-services]
    environment:
      POSTGRES_DB: activemq
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - activemq

  message-app:
    build: .
    container_name: message-app
    networks: [backing-services]
    environment:
      DB_SERVER: postgres
      POSTGRES_DB: activemq
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      MQ_USER: admin
      MQ_PASSWORD: password
    ports:
      - 8080:8080
    command: [ "./wait-for-it.sh", "--timeout=100", "activemq:61616", "--", "java",  "-jar", "app.jar" ]

networks:
  backing-services:
    driver: bridge